# Generated by Django 4.0.6 on 2022-07-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, through='articles.TagArticleRelation', to='articles.tag', verbose_name='Разделы'),
        ),
        migrations.AlterField(
            model_name='tagarticlerelation',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article', verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='tagarticlerelation',
            name='cur_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.tag', verbose_name='раздел'),
        ),
    ]
